on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Hello World
        uses: ./.github/actions/hello-world-docker-action
        id: hello
      - name: Show file contents
        run: cat testing
