on: [push]

env:
  matplotlib_version: 3.7.0

jobs:
  build-arches:
    name: build-alternative-arches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64","ppc64le","s390x","armv7","i386","x86_64", "riscv64"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/run-on-arch
        name: Generate Images
        with:
          arch: ${{ matrix.arch }}
          distro: alpine_latest
          env: |
            matplotlib_version: ${{ env.matplotlib_version }}
          run: |
            ./update_to_edge.sh
            ./install_deps.sh
            ./generate_images.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-${{ matrix.arch }}
          path: output/
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs: [build-arches]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: create .tar.gz archive
        shell: bash
        run: |
          mkdir ./matplotlib-images
          mv output-x86_64/mpl_toolkits ./matplotlib-images/mpl_toolkits-x86_64 || true
          mv output-x86_64/matplotlib ./matplotlib-images/matplotlib-x86_64 || true
          mv output-aarch64/mpl_toolkits ./matplotlib-images/mpl_toolkits-aarch64 || true
          mv output-aarch64/matplotlib ./matplotlib-images/matplotlib-aarch64 || true
          cp -r output-armv7/mpl_toolkits ./matplotlib-images/mpl_toolkits-armv7 || true
          cp -r output-armv7/matplotlib ./matplotlib-images/matplotlib-armv7 || true
          mv output-armv7/mpl_toolkits ./matplotlib-images/mpl_toolkits-armhf || true
          mv output-armv7/matplotlib ./matplotlib-images/matplotlib-armhf || true
          mv output-i386/mpl_toolkits ./matplotlib-images/mpl_toolkits-x86 || true
          mv output-i386/matplotlib ./matplotlib-images/matplotlib-x86 || true
          mv output-ppc64le/mpl_toolkits ./matplotlib-images/mpl_toolkits-ppc64le || true
          mv output-ppc64le/matplotlib ./matplotlib-images/matplotlib-ppc64le || true
          mv output-s390x/mpl_toolkits ./matplotlib-images/mpl_toolkits-s390x || true
          mv output-s390x/matplotlib ./matplotlib-images/matplotlib-s390x || true
          mv output-riscv64/mpl_toolkits ./matplotlib-images/mpl_toolkits-riscv64 || true
          mv output-riscv64/matplotlib ./matplotlib-images/matplotlib-riscv64 || true
          tar -czvf matplotlib-images.tar.gz ./matplotlib-images
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'matplotlib-images.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
          tag: matplotlib-${{ env.matplotlib_version }}
