on: [push]

env:
  matplotlib_version: 3.5.1

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate Images
        uses: ./.github/actions/export-test-images-x86_64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-x86_64
          path: output/
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: create .tar.gz archive
        shell: bash
        run: |
          mkdir ./matplotlib-images
          mv output-x86_64/mpl_toolkits ./matplotlib-images/mpl_toolkits-x86_64
          mv output-x86_64/matplotlib ./matplotlib-images/matplotlib-x86_64
          tar -czvf matplotlib-images.tar.gz ./matplotlib-images
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'matplotlib-images.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
          tag: matplotlib-${{ env.matplotlib_version }}
