on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate Images
        uses: ./.github/actions/export-test-images-x86_64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-x86_64
          path: output/
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: create .tar.gz archive
        shell: bash
        run: |
          mkdir ./matplotlib-images-3.5.1
          mv output-x86_64/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-x86_64
          mv output-x86_64/matplotlib ./matplotlib-images-3.5.1/matplotlib-x86_64
          tar -czvf matplotlib-images-3.5.1.tar.gz ./matplotlib-images-3.5.1
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "matplotlib-images-3.5.1.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
