on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate Images
        uses: ./.github/actions/export-test-images-x86_64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-x86_64
          path: output/
  build-alternative-arches:
    name: build-alternative-arches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64","ppc64le","s390x","armv7","i386"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/actions/run-on-arch
        name: Generate Images
        with:
          arch: ${{ matrix.arch }}
          distro: alpine_latest
          run: |
            ./update_to_edge.sh
            ./install_deps.sh
            ./generate_images.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-${{ matrix.arch }}
          path: output/
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    needs: [build, build-alternative-arches]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: create .tar.gz archive
        shell: bash
        run: |
          mkdir ./matplotlib-images-3.5.1
          mv output-aarch64/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-aarch64
          mv output-aarch64/matplotlib ./matplotlib-images-3.5.1/matplotlib-aarch64
          mv output-armv7/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-armv7
          mv output-armv7/matplotlib ./matplotlib-images-3.5.1/matplotlib-armv7
          mv output-i386/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-x86
          mv output-i386/matplotlib ./matplotlib-images-3.5.1/matplotlib-x86
          mv output-ppc64le/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-ppc64le
          mv output-ppc64le/matplotlib ./matplotlib-images-3.5.1/matplotlib-ppc64le
          mv output-s390x/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-s390x
          mv output-s390x/matplotlib ./matplotlib-images-3.5.1/matplotlib-s390x
          mv output-x86_64/mpl_toolkits ./matplotlib-images-3.5.1/mpl_toolkits-x86_64
          mv output-x86_64/matplotlib ./matplotlib-images-3.5.1/matplotlib-x86_64
          tar -cxvf matplotlib-images-3.5.1.tar.gz ./matplotlib-images-3.5.1
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "matplotlib-images-3.5.1.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
