on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Hello World
        uses: ./hello-world-docker-action
        id: hello
      - name: Show file contents
        run: cat testing
