on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build x86_64
        uses: ./.github/actions/export-test-images-x86_64
        id: hello
      - name: Upload Artifacts
        with:
          name: output
          path: output.tar.gz
